import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebars configuration for Physical AI & Humanoid Robotics Book
 * Structure: AI-native Option C (foundations, modules, hardware, capstone, ai-features, meta)
 */
const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'category',
      label: 'Physical AI Foundations',
      link: {
        type: 'doc',
        id: 'foundations/index',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'foundations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Core Modules',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 1: ROS 2',
          link: {
            type: 'doc',
            id: 'modules/ros2/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'modules/ros2',
            },
          ],
        },
        {
          type: 'category',
          label: 'Module 2: Digital Twin',
          link: {
            type: 'doc',
            id: 'modules/digital-twin/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'modules/digital-twin',
            },
          ],
        },
        {
          type: 'category',
          label: 'Module 3: NVIDIA Isaac',
          link: {
            type: 'doc',
            id: 'modules/isaac/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'modules/isaac',
            },
          ],
        },
        {
          type: 'category',
          label: 'Module 4: Vision-Language-Action',
          link: {
            type: 'doc',
            id: 'modules/vla/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'modules/vla',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Hardware Requirements',
      link: {
        type: 'doc',
        id: 'hardware/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'hardware',
        },
      ],
    },
    {
      type: 'category',
      label: 'Capstone: Autonomous Humanoid',
      link: {
        type: 'doc',
        id: 'capstone/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'capstone',
        },
      ],
    },
    {
      type: 'category',
      label: 'AI-Native Features',
      link: {
        type: 'doc',
        id: 'ai-features/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai-features',
        },
      ],
    },
    {
      type: 'category',
      label: 'Meta',
      link: {
        type: 'doc',
        id: 'meta/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'meta',
        },
      ],
    },
  ],
};

export default sidebars;
